apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ../../base
  - secret.enc.yaml
images:
  - name: ghcr.io/calebsargeant/deskbird-booking
    newTag: v1.6.2 # {"$imagepolicy": "flux-system:deskbird-booking:tag"}
