apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:1Ph/t8K5b2tsSAZvuskjzs6ms27luF0Rcr+GZFTIRa352B4Hn9sNn/Q4poDXcdf6CEuLO2cruDj2O252ZabSED7HlsmGZIZOUfK/gdbLAr8pTxM6FKAB04eV7mF2FEoOlczqSEpP+OffsrB7UN11aFdxMHzJOscCJWbuPMG0HFjfVB22QMRJlTYZMkYZOQEvDlhG1A5677I+OaRCYNL8voRFV1/2HblQ7zeYlxDDosdX6gptJK7DzNvUxhf0miO2UoY/XQr4GLHAjhdsdULoI9mNQF1m94ekIdoGCluYNnC1VPMXwSfcU0gVAeZjFhCfPD/9qayC3D8knTQ4RU0e/DzBUD7QfE8RNiTBzfb7fMKoq3+5ZnvLNkMsyX9io5++MRMjj1SYCCkORJmhVfPNh12l+HTA/rouF1Jj3qaED3Tjc/9pyGpFGB0wLgfkUUDjOYXcCan+qw6gVkvobEQR18zJQZ4H+DmwlBs7KX1DFscKaImAK8nQOky9K5q/cSzSxovxx2dPITvZupQjeU0rf4rzwoQ+ambCSj+y6ORbZByQvHjQZX+H9Zwuih2BycpABqO/nDBudqEtlFVi7CVydEovaSfjhJgi3U2VRdy5eio8b5NwSSi9Ner51GVjI0FmN1aUE1J+5xE1qfjBvT/Q6GcJRUSQhrSxbmiccPSYevHgz+BmS+IqBCqv5c5jJExa+/zFAHUpiXlFV3/583p+CjqIE8Nzk5K7khIrYIQUkTZRseoF4Nr+6d7w+bypeUFSp74iVlAJ5W2OUj0THg0J9fYqiDMLg1nASV0rVEgD8ZrGPC5wBcvgFuw4yHqTu2lOLiwjuw/CEAkl5YPS/76aaInXKD+/osAGukQwKQ9bWn5q6KKGoys/HDBo1evelCB9PhyT0ik76ZnPPvSGtI1gV9eYOuLnepfeqQnwdWhdJ0iUbZTo38NPd7eOx3EiAhWiXdeePe1OG9ve4hIXRFLPUNX1yveGN2dIdOS8zubtnszLUfjn2rywtmt/6KO7A/vbshkE3SRDTrv32PjhELhX/H6E5dYpsblejnNc7iaMh7zuI+A8FxXCzo+FnXLgDnMOjPD9LM89meJyPTrEvCOPEXwvvTYrfvNWz+fGlqw8AIYcWGtj,iv:00cxaEilkQD9abSPaoxECO4Qj/IHPpD6BYhAISpSaOE=,tag:UHlL5ppCv5Trz9c4WhZ+aA==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:e7rnDJ95v5RA,iv:WH8qwkModRhJrGyeOfTfmMar5ZXW8AyjrPpOusflXqw=,tag:ZWsdzhUIyj0YfGBhwi9ByA==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:AQJtmUud+SLeoLvt,iv:HOyShgm/ZwDPcTqKZMwhPcSJ4wadnb13U+uVRvXQ8qc=,tag:q7Pih3UmRrmlINugJW8foA==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:55kFUGc=,iv:xdzvcT3aC0g7+kJyt9DHqNzCiNmBKC3b3f2WUTdFPqI=,tag:XOCGCTmN2GmSaw4WQud9vA==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:J9EDmo4=,iv:FMDRZWgyYmaDIWiBGd+IWk+IPzX9JS86vGFObNuwn90=,tag:zJjHKkIUGzusyOcBpL/mRg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQlNoY1dLVzVtU0VKVk9D
            bzJrQng0aXhiTmEraG5ZSkxQV29hRDF5YUN3CnBoN1krdU56RjNFTWJCZ0RTUDlz
            ZXNKSm85WEM2UkE2UHdYMExCUFBkeXcKLS0tIFZabm1YREU0Y0UvOEUwc3JNMktu
            c3grSm51bmEvb29SVS9xVC9YekxxRUEKq+i/GItT3bAvIkae9OPrCgUVBqAzC32b
            u1SKUze7PnD9P/RrXmxzMpbtGDz7MeAHhUmR4uZo1/1c2MbLZV4VIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T19:41:32Z"
    mac: ENC[AES256_GCM,data:7rc3K5Ko3hWppjPvQUgCL7K/LlnWI+gASipT8APO7YHZJqckEofA9/CtEiRZVYTjTTETvDm7eygafmJSI8EA94zWbaPjI8Ch3oe3FxJ4dMf5Q5mqz0J0obn/SbYgWhHYvC0hyQuwV6CEQFQCenKms8T7tKcp5EFL5ajCDE+EFd4=,iv:qCvtufDoo0uMWEOj1SIPzom/V1ctWuJLsmxDksaCRTw=,tag:Ahxi/2vHEwXotJ4uR7llDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
