apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:UhfBt46+iUfSuBCQx+QjLGMalPRs82hEB8Sh3YUYpJF2e2dCcYo3g+LL6Hj1Krb2gSnRavCMK/DiLUANxiHrHLY+VUMN65yH1FsxZnFjTch6388vYMHtvou2xSHDPFVm39aaDkGTX4MGWDjI5DGGLS0TrQTQthFZMkBw+jCFrZCdL0Fz50QIy/bL+sriHEv1yTyTrfBxOtoKaBQiDJxmHGhmKhsAoQncmMGPrP2ApSCIcy6o38DJ229PcRM1C+ZIOaSF65nU5CJY/lAaAcC0ROSBH5q+ZFTkMAmM8M2GxbDWziRO5Y06wyHQjb/lSJSZ4iFg8AsM6V3iC7X7ykEdtPKahViIxTzRhD1dPIaBk3qAE0Jtfpc60qloxN5Z4GzE+IX50IGOGWGMKVkIMo+Ta0+C4SejF6+U9qAlOjN9pRW9sTxOCtxZiZ2Gb8RdUL4zzTXZRDoyBVuXjv+I9dWQlfezdjapeUVfG+SUBboGprnjSQ7HqPp4kxLB2rABZx6e9GQMpi7z527jvfbpncEc4SmO4d/13WUkx/kQz0rLcYoWPqL+1Larkk50wOP/C9L6S53hjXE7x3h8QnSE1K21znanlR2S9HTQHX72drHxYZDErATVo7I1Gv+KjTRuKIzbQ5DGFPtBZB3ciH4KjcWtJT0kmEaZTwmLI1+fwjCYMsjfMlnIkxRn6P9e+2dhQG7P3Yc3dmeUjsISb+giMqz9PaTNrMZpl5eOPB7p+EBZmlSUx4aJ9cCDl05MKGRNav+BvWyy+3jxs5BaKsaQk+A1qv+vbIa33cGW9fv5yyTNRHQzO0w1Kph7+pQ9BDcC7J2JeFYR49ko4CIO/oFAdd/EAoPOOoT9ogCcsaXTxbLpS+nJ5pt/jGi6r3X3hmawu5hm4iyrY8t8hCxr9HduoD1lO0VL/1ee4ZQrziaK8nCfyK9YSLgrNywtdv5EisvHALG9RsLM34tb0JF4efiTVLTuqWVdoLRBSyDH7qIaM3/b/dRR6hiZb3GBIhE5rY7oafzYjYqL3U9eE7L0XLNHB8qK+hcEZcvg9czwRhm54SPoi7csfV1bh7WI/C+HEwYPJyn36YHX2Y5sp3T/f2PHF6XAdP4KAxCnVqrGJSgIp+TpRyPdXRTA,iv:YSC259rFX+WpgN+iqMpfj4PUrGVlOIoi+Dcsa7GoCp0=,tag:JL5+LALU9Pjzj6e91hG2tA==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:LCO8M0jJoVve,iv:o9B2euC+LsS8PdabO4ooJOHMgfrIqGYKIoLMf8utgek=,tag:2FP2zqbbAO/EDE7am/jUWg==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:1Qj9v2EJYLiQqdXY,iv:XSwQ5Eyy9+5XzBnlVtqqZVus+feh/AvKC1B6VMapj8s=,tag:sPeeQIKKcFdlGPyYXqHBrw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHKzZubFZYQzU0ZzNQdXZC
            T0ZBdm1qWC9sb2VGbFNxcHhJZkhhTkpkRkE0CnpDSVluTk00THUrZmpEcWRJci9k
            R1krb2NaRTBFWGxCWi9sK0g2ZDBocncKLS0tIHZCZlNRbDVmZHlsS3RXenpETjZK
            RVo3TGxyVXdFMVRTT1NEcThQdXNlaHMKEPIu6Ak4ZKrjQb4wlYavQ4gH0Cm08dyO
            cTpu1jMafuHZozKHnD/dXj67AFgNZbYDZn/ZM3zoWE0kK7r1IJyS2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:58:17Z"
    mac: ENC[AES256_GCM,data:uScYiKYq6IMAl2T9JKVmrAFefSNHQawscIvfamd0T06jOmdfe28/Wn3jZhAoqrr6kdYWi1yv4A4jV915Zt74G4CNrL6Ev261CqYp8fx9Px3DvZ3SVuhG2W81n+x82CC+AvluBmwdXQtfh7cAUvs9AcCO527oMCr/HYGjt9qEVk0=,iv:N6VYXCdZ1NMB9ucbv5ydI+EyrGpdDbEggLlUDNWvoYc=,tag:TRH3bhK/V1geAEefq08bjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
