apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:Cn0HSO19SdSSbjD2gf8zm5BxcrKqyfIuXwNmnUyvymI5zCJmlw0h8KnNt8uA/t5U8bPjOiQa5U1r+tugJRZT8TxaS/iAuL4LFLe7O/lqFcgoVjdPKmNV+4yJp/+8/rmzHN5av9zHF1xaS4oqGb12Nlin2epoChqVROmkARaasMDhe+GdY+eUqDSBNfs/YUwPh66gREo25Fo7gtltIpHKCg4qNI54TkibNfH8LwGVxfibbpNc+OOWdtPpy9iT3dm/BCTQU3cGno8GZNz++eIf0lWFW9txlv+6glu6/UWwIkb09Tdtt7p+YWIyymH8IPY3jKkZkoHYscBW1Q6DQpIZOCBPYBMkNkMbNwxgAJYxCDTWb7TU/tYaRyLW/KLK2/p7++v1hL6GR0xE9467SXfx+dZBSJ73q3r3VfalnR/MXCN81kG5E1pbRikUsPLGtLtb20S207uwu1B2DeJxWxClHE4StHqEFhCgZEGhtL+R7uOvniS9iNBmb6KC2XO0Yby/sGFSAtoDTvlOqCNvKBn4vDbrvhkTCoS02p5+Duixx3ofCs+E177y7TSkzSpkpbpRaXSyGZfA16APc5wnC1gMfTW2iCUWJ7EdeF6kT95hy7QoYxLj1hlT9Js6HSH4BgxzMqajyt3zfdeOv3yaHxfmd7y/Tc+slyUTPT0hTIrAlcRIlXtN28q10Az6ZGkO127uqOG/FeOmN6/jK1kb+knZFFY0GykJAqMXm6SktVkllB0TJY24xrs4T0ftSy8JP0H5gsE50gMrN1YQwA3uVbEbDPVaBIXyBjdsxHqElE6MeJGgWM9TJKHM7t8WAGUfI6Na2wUzXsbyywxGY2R6xoPphJssXQgIMSBeOdQ368vf5VLzSjmdYjEnz6TFKaCe2/ryvcVAh51j1gScwHav1c7LI98BCDW6+dnGPxA0r/55lnMEwlr/MKZdybfAS4RedXmdLdUf9id+vZjFRu4yq/DCacIxCPcOF//ncnHb0KG6VVvzsHbxh0J7p53WXiGugpB7YI5uZpSBMmVwy26dJ5eRpULKNnKCXSFkJlnxX4PFZDSRmWQYB2FluZo3VzdTIRW5l9br75uYgZKN3m4y843X4HBu/UbxYkIjR8PjZBoKuchqmaS6,iv:Odn+wmtHCby79erOCNkYI0OuguVp8IJ9592Linbgdzc=,tag:Ajb2lF9v1Tuk1cmB0aW3RA==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:e7rnDJ95v5RA,iv:WH8qwkModRhJrGyeOfTfmMar5ZXW8AyjrPpOusflXqw=,tag:ZWsdzhUIyj0YfGBhwi9ByA==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:AQJtmUud+SLeoLvt,iv:HOyShgm/ZwDPcTqKZMwhPcSJ4wadnb13U+uVRvXQ8qc=,tag:q7Pih3UmRrmlINugJW8foA==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:55kFUGc=,iv:xdzvcT3aC0g7+kJyt9DHqNzCiNmBKC3b3f2WUTdFPqI=,tag:XOCGCTmN2GmSaw4WQud9vA==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:J9EDmo4=,iv:FMDRZWgyYmaDIWiBGd+IWk+IPzX9JS86vGFObNuwn90=,tag:zJjHKkIUGzusyOcBpL/mRg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQlNoY1dLVzVtU0VKVk9D
            bzJrQng0aXhiTmEraG5ZSkxQV29hRDF5YUN3CnBoN1krdU56RjNFTWJCZ0RTUDlz
            ZXNKSm85WEM2UkE2UHdYMExCUFBkeXcKLS0tIFZabm1YREU0Y0UvOEUwc3JNMktu
            c3grSm51bmEvb29SVS9xVC9YekxxRUEKq+i/GItT3bAvIkae9OPrCgUVBqAzC32b
            u1SKUze7PnD9P/RrXmxzMpbtGDz7MeAHhUmR4uZo1/1c2MbLZV4VIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T19:21:50Z"
    mac: ENC[AES256_GCM,data:JrXRujmSmnLUFw21pWjIKH+7Y+yPmYZmiqmWmEJPv9fI7L2UNE/mZhUcr0WT7Sz+/QLnZ5K6nwS1eJKEv0rTljinZ0bZJ557EqTHpx6Pwx70w69lvhmzo65AzIauHoCpI2jSvpMY++sxU26rY50zwdtGcCTHGZ/xY7bjumRiDIQ=,iv:tj0umdngp8NU0lVrdc3tsZejhsjrWThE4QiA+guXlzo=,tag:ohy++qTfRmF+pXIAhdmuAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
