apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:RCFOvtSIt75ekJmPH/QAbkgJp/zxlcR2/ZBj66ds43IAI703mJ4BCy71E+scS1AHAqURxfXPpNcjhNb3LjLlkeqb3kDGe5UqGwsDOeMv7pkXL578zNWYU3/gaj7XB/lFc/WNCjv+MhWHfOGxnlHK4nGe9M7Ue1Ci4TexmZXtLIjFGNMB6H/hChF+HM5ff0FwMtmmp6advAokPVBRaXLVp/sYc7zvClfNVn3vStD4TTotKi2CAkuR7oamJiTTG6ZdmPdHLOojUfnz3z+sRqVrlsfvSnZ5G2cx8iFXWPd/hyv3oqYyXWtVDM3lksumTYN4Z4Z5NEg539tgkq2nuiBQOEa1ljoq/4EcmDvW+0o5laIhKDi66Zeu5woCKaDP9SFP5vP4PTw83Ux0BHmUNHPQe1yoe3rAC+NVmbBvGoVjsTshz0Bed0I871MeOSlhnx/F2JLGJwDG7p3eROWpKKlDiYQDZgxk28/GcmQvnpRPwB7ZJx626P73PoMiGNA2H1h1Po9liptsnI9LBmJFOEN2nzRgu+TBaBgTmI6GO6TMV/Gu3CUOJ4dvrQmTMOAOFBw9UNa8Wpz44JALTmqPe9P6kbToFWJVuXemCLQGhiQhUxetda0yj5LmVdx7QecKr6kC9ncvqgkqpgvqx/NjSciKVs17BaXDCGcAIX0P+l15Y0iDF92hLSnmDJQgxya+NjPDNueJCnm8CZCA0dRg9bxgDBHqmzF0evgcTQVt+NH5PzuiFhKuKxowQRiQz3riujQ7tLn8mZfrIRMk/CEHYMgTav0EZerXGHv/2LBdjAG8RWUBOqZMyIeEpVfsWVfiMO+nwe5UOfazK7/fdtjjIg12HelgNRAyp/9ktYs4ruJCH7bXD/3h0Gd7N+pJ6UacRNedm7ZeXGrFhPPQCtgUl92GzXFGq3D3PSjtjAdcODY3RbepK0Reeo8vID4Fe1en1/1jDuPiEiYlBaG5NYU5y3gu/8QD3/AY5eGZmY5TjkUE4LXLnJ8i7fdPrgufG5IqXaxnH036D0c0pCXJzd0tYhIQWtwPr1iYqVODjhDwwSMjtbApl2U+Zxzw7Shy4B3Y3zFjCqA1AY4frUqvTf0xSLDhbnS34O9LMDlyCzqqWOK/pPh6qele,iv:As8KJpkjj9Wglr3b8C8x5/e2rmItHFIhWLsDV25+C7s=,tag:WaEkHa1mEjpfNTnbBam+Lg==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:sGmRpQ+8SfAE,iv:WlRY0YQpokpYIKZID4Ca/kp2oGVqTccE6muQMGJ6coM=,tag:wF4DjFrtjOPfgwGJSlHk9Q==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:F07zujKn5GXqyV0d,iv:+ulRGo3PJTMyUApilMA4eVHHwtMsReeglADrnZDorvY=,tag:Z03z8lY6ljtj6pqiDoISsg==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:bBvBA1g=,iv:j/hvi5Rv/gzWs20x6kpZbow1gbIz7BNFe07iAL0WLak=,tag:EiQdCSkCBFmMnfnZWfqNbw==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:deV3Cp8=,iv:JWiLUmtBqWBnP+U4d7PgvU10EeH9yy7clFdaz29XcmE=,tag:3OHi8gyNiDUtl3Uf8CJSJQ==,type:str]
    PREFERRED_DESK: ENC[AES256_GCM,data:bKEHuOjK,iv:Gju8Xqz6WZFqmwb/OkcDNaglc9QBZgrlHhN5pFuNb1c=,tag:K2dsWw9tbBK07GilF9m9lA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTlxVE5LNVlLeVd6OExi
            NlM5RGFsRExQRzJiR1dkZUkyMkdzVTYzREYwCnlrbEZ1NGdzc2xjK3VMNXVPY2RO
            RDlleEdpdXVXMms1ZnJVTW5MSEhON1UKLS0tIGU3UC80TDA5TVlBL0wxRHRWSU5a
            RWFTUVNiQzFYZVVqUENSNGJ6UVI1eEUKng2vILRS6l+e9InjaTtflJHoynN556V4
            NG4AKUALWejcS5LEXVIBIpCOY+bJVGWVGXPXKpgn8zICWwxAE3Jvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:37:08Z"
    mac: ENC[AES256_GCM,data:hIqVC3NRswCsoRXOBzrl0euDylWDP8TAERJ8Vr2OwxRY4iVhorOKIPckECmXYFbRMtScf79t2ZBMoMXIVKrCXIIvQ+c5W8cDycIO8YASyW86maehzH0GUYqKQ8q/Jh3Nxu5yEOABaYwZxLJ0GTjVae7brbRWUPIOhwxOLUAHkxs=,iv:ogOZEbwtJQM3bS7F0L1OnJhkEzU0khq8eDN0rzxDmU4=,tag:nOcPF/osPBIijtjgX7bOqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
