apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:vVpRJbxRH42QZoN/rMkntbd40J+Zjasbgy/0R/kL4GlP1qKnJiDu4N0YzWHEaMvgSenyNPU7uPSukRzBVB7B63+kvRXABRDhRxiarxq1NAbcfYQ0tCKlrj5cdeBbGnhag0fGZDEL7TPtJN2zht0bqbHgqT55ObxyktLvq/0m1gaeKMa7PyESJntXdzel/OgNTZhbpGU+C5F10sZ0WQ8JZ6fiAN6cmOeg8b10dAvkbMHdoeyIbiH/OADvbhvhapUU3mOcONqFvIukRS0ibypQJnws9P4th1QxV1NGVf4xvSadsUJ11wBrgzNmAYLcEMM/eaVXPIKPJpxaxf8v6PiLD2ROk2C/LcomY7OkbVED3Du6uA3ZHUUezPvJKhafWFsKHb6BCcJKnpet10/28qFVJYP8LdvnKMzH/T4IfLhlzgryAxwYhEb1OyQs104Gx8Pz1iWhRGn4R1QPk9HY0aBy3OHnXAnr5MdOAZ8bl5X6RPyL1qjtQV40SPTUTEI3nfSyq9Wn1mk8BznTEV2wzj+fClo0j2K+XqJgEohgztMFhIdMZ7fDjPVxlO6I5pp0vx+1PEazXEKvcOPXuPAYVb4baHNTDXCD0yEgt5ycjsZqAGN242lQxuGw0BF7HGOxBEqP7Ve2Hc847n3zMrBSZTGaJDkDQeWzYDFMtdbI5Vm/sPMMvBl+YoKdobpImwZnQN1yeiuqdqnfsVse6UQ57tc2Uljvu+n1GQEviKqFDxhGytfcaPXSJ8xOFQ8HJ2CRoB5arB6eERTbB99zb21JQCJIL1jQjkrJQ1aj2D66OQ2DGFFoqzQE4DNpVgiU+wfKuNfpfhM92AS5ZoI1pfFmh409M4EpcQkPIDaYeUj0scRNTkIlsxlE2aatmpPMQkQelXIykHO/w/Egyz2wFpgKTVkzh8UO2l8XvFKnY9pvwwrKyOh7OTUJlbMszo73WWnJ4WZ/FWoIWk/kYQZMnQ36yROpz1nslNh0lgQBp/xE23md9P7DAszblQSw+TZ7pzhQzjrrLhjo47k+Tz8ZwYkKm97nvrLNwjEv6P78naMbI5O6j0dEZMeMnfadzUNv51/ecYvF8cNUpt6eUNpfE+ejlN64Qm8v7oaaxWaZrQxJsrBRSW9+BCGs,iv:SY+/hjBXj00JkHc13OM+76DX3g8+Do3W2FQbTe0weQ8=,tag:Ww7A99Xx9sfkrQrdNrkpqQ==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:0QhypGrHuMrq,iv:mLXtxBOQ8Lt17MztwsEYnGOtjIiwtWf0LvIu+HVKTHU=,tag:BLxZnjtjIZf/azPAwWiEsA==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:DvdmaWRKt6s/1OLv,iv:Lq3LSlmt+6N5xfFE45uAesQncXED/kG6W41NJitI7gg=,tag:tVosf2A3JzXeLIUfoIypKg==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:+ho+OTI=,iv:cjzMkLfqMAe8GcApVGTiWbt89r+OyzJUTgDDrHihlmg=,tag:jepYs8wWmcdnxuX2Un4E1Q==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:S06Jw5Y=,iv:Y8yUyzDRhgylYEW7imSWD1h40MgedIlSpxbVvEkcjsM=,tag:VKeQUx72LDRJ39pen9Ddfw==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVm9pOHdLWm1uMzN4U29K
            cXNCN3NnaDVEa2liMW5BY1dSTlJTQU5pVWpjCmZXME4xOVB1VGdIdXc5bVlFU2N5
            aTdrVTQzWis2NGVNSWFoU0lsMm5BbEEKLS0tIHBTV3ZUUngyTFFtc0s3NVI3Tk1R
            T0RmYWNsV04zajBPMVcyUHhORjExTGcKHHrseGUd9E3zgylbwQHGXCKcC2NZRuHk
            agM7X2OuawBxZbfk9Yq/rtpLUnRyjBSUKTd3ChJPpDuEk25u2mHJNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T16:12:03Z"
    mac: ENC[AES256_GCM,data:hZ58ykg2SY6MqdZ05rXYfasWDHgINK5BIk03Xg760q4sRY1jtk1zIWOOys/cEMeVQKqh5qbqGXTfEEwNfc9f2lsjCSVtdv489S0qHI8AbfrzjoyffGDcamaVqkt4lYLe1zA9SAu5qNZQ++GGFMDBhv25GDtEAvrZFQaCEJ97Hhg=,iv:chbtTxT/BfPVtqpui4l92zBcbwjlBZjv8IiZupPLGmY=,tag:zNj0eq+03V2dKfvP62l7XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
