apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:alICs4Zc118bw0w+brgaZ8m/GtMOyEsbhxj69YchktBXuby8Lm0XkQckfku+af9b/Ic9+EpSoLoTaWmih6BC2G8j4RM+lXyqUHdDHqSxUfy1XcPSVssHLcuzHcUh3OIzx+PKMWvSYolKCILq37qLFmOMv4EM7MRg8j/WQ0A5IG50ech26zW4UeoVhS80kHyDMvaBt0gqHzGIHDM/yuSQUafqxp5EUit5dK0WJhxheX20SNJoQ65caA+j06qd0dYBfrN9rlMzFz8IexyCVXdv/YoFTBQXOBUzZfenXUcL2J3+YYAEmm5wDa8pmQhbthkd39QyDHlB9PFVEqTcmzd/vH/BWCp91uOR/anqIJh9+80yZ8etb9c1oeb/mJxjnmTW0fSByh9WwiHlFXbTJoz45F+gxUM7JwsTsHnCx6Uk/grxBbK1Y5TMpdADY8APWPkF8eVmV5osrWo16JhM+A/wSU70RGcdIWvAUL5PmXFBT5GeEYxPo2bx+z9NDO1klUs1lER1iuHBJ22bsXTDW3AmvPmq4uJGsQjnUBYGeeyKsQ+r7YynylaCLnW7G6UeUd/IRHRqpZmZdNquXK62HesBd50kkMXQ3ySYxGWgDWrDHIyIvVCDicE+mWOHKbB3vcaaulU4RUezO+Uj0Ok4eJTTQhoBwjkrJTZA6Xk/gBYqIkrDz9R/jd+3rKZoMxXv2vqTM9zfOYzbpRp6gfc6kDf7K6ErWmioaZtfsnzkJeE220XCHgjQgtcE8aviWimaL682LhppFH66bI1wIkfXSkoOxQVegxlllHt9ZPWIarinyf8J+HGj6LJ+d8EP+AWrgDgxAfPyShfV1pGHaRjYwaDJximtsbICEuqBeQJj2fjyuQoSLumn4r9N+y+aFfeecYQseJ5x4pCt70eirbawbbpnxwyHKdltO4tG5UVluEHcf9SWvvcrEbDpcPwstzmGnScDXV8WKGL+aVs61AhzHtIrLfnis0QBYrMSn3tuyia/CBPsWT1y2TIOEgY/3bE90kAeGsRBDe7azewtJkOU9oTTPW8gcCBqzVCRaTz+ZhWhwHzndlrAWlGCVv7DF4b/dQNBFEJ6GZGpY4puXC2cBmzD78Qqp8pmiUa3bF5uGE+MkJcXoDxD,iv:xdGNQ+3Z9wLEBNCd3dZ71i3TOm3BUhIUKB4Bw7sM4wA=,tag:3mmbNj+/lNACtycqX0u1oQ==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:sGmRpQ+8SfAE,iv:WlRY0YQpokpYIKZID4Ca/kp2oGVqTccE6muQMGJ6coM=,tag:wF4DjFrtjOPfgwGJSlHk9Q==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:F07zujKn5GXqyV0d,iv:+ulRGo3PJTMyUApilMA4eVHHwtMsReeglADrnZDorvY=,tag:Z03z8lY6ljtj6pqiDoISsg==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:bBvBA1g=,iv:j/hvi5Rv/gzWs20x6kpZbow1gbIz7BNFe07iAL0WLak=,tag:EiQdCSkCBFmMnfnZWfqNbw==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:deV3Cp8=,iv:JWiLUmtBqWBnP+U4d7PgvU10EeH9yy7clFdaz29XcmE=,tag:3OHi8gyNiDUtl3Uf8CJSJQ==,type:str]
    PREFERRED_DESK: ENC[AES256_GCM,data:bKEHuOjK,iv:Gju8Xqz6WZFqmwb/OkcDNaglc9QBZgrlHhN5pFuNb1c=,tag:K2dsWw9tbBK07GilF9m9lA==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRTlxVE5LNVlLeVd6OExi
            NlM5RGFsRExQRzJiR1dkZUkyMkdzVTYzREYwCnlrbEZ1NGdzc2xjK3VMNXVPY2RO
            RDlleEdpdXVXMms1ZnJVTW5MSEhON1UKLS0tIGU3UC80TDA5TVlBL0wxRHRWSU5a
            RWFTUVNiQzFYZVVqUENSNGJ6UVI1eEUKng2vILRS6l+e9InjaTtflJHoynN556V4
            NG4AKUALWejcS5LEXVIBIpCOY+bJVGWVGXPXKpgn8zICWwxAE3Jvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:24:50Z"
    mac: ENC[AES256_GCM,data:8l6Y+KeFvvRH0lWBaR/NWU+p4JRfKavbp4sz/98aF0o7rFQxX/l/CMlZ4N145ts32Ig84DKILsRb+QA7wXdNgY8rIX//AdBEb/PCaQR5UtOvUFkyrdw76DvlFA01Iy7Z5HzH8G1y59hYGfd+51nEepsHegCNFTsOOud7x3vlr9U=,iv:0kF16i3H4zPOwFADVy83MO64FAQOrbNcgG9G3VryCRw=,tag:v20aM5raG0+q72iSsrPVzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
