apiVersion: v1
kind: Secret
metadata:
    name: deskbird-credentials
    namespace: default
type: Opaque
stringData:
    OP_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:eWk11lGj9nvpn7LcNrEXogX2YAi0lS1iyqAV5AzL0VT4CeFvORtmvi7NCXCPkn46Wrq0atOzy2T1tVdpKWINgXumoflDmO87WJQu+gr/5xabY4ic7FFPAjLcMMEUP2XRb8luLH2PP2EN4DH7Kv+k+FebTJi4LT7GVhtZuVANlzlVdVO1FiUML+zamCsIRtoc0JRpydtXNktM9TLZOLN6is5dFLSN+AVLf6ZXGXlhaI6+XaMOniaMxsTDciVCcYHjGK8lg+lOGQw3zCGXvIZ4cvtTfB4m3Flx/QO2aH/L47zyWC1Unyy6VYrMijstAwcAKKYE+sTj4DAOaWR+7u7RMsmWi5VVseHUMm/yiLdQKbxx2SNlnjlUbbrpg5AM032LDAN1VVTOBcCwyyVP5sW/1rUwzBANCSkx0ojaNwOTd0RcmsgWzPYTEPPLEvg42IrvvuEyXhC/PoTVmpmsxBqULenCRqzfKrjTs88u99zsKcqZ8M9lo3nDx36L2Q7uoKGnKO3wTF71a4JKdsrXeAB3a1MotsZj6YdJiZDtFndvmSb2L2q6cefmN4TIR4FZ9U30D6kwyXeR8t7imdOEf/zPJCmJEOgxlU1B+KP4xijOZihe4zX33FFn4nB4Zar3L8Gxaj5EMQwykQxNN5qY6FXk6dwn9XyY7MyXvrBxOW1BvrBwcXic541RqRSHjN/KMkugqW0mzfPSnRPQu+iGsPGnbiGFVH215dZDJ0/ErbOybf04iBb1vHWACvLp1V5cTIZ6qirgtRYxIxIgRqIpNC4TpaziXKuMLmBP79PAqeyx5aPw5v8NXA7oaLd37ODTof32JqiAs+UwYVwCPeHVrUgB3goU6oCfsEo14XFAWcnibRIiKP2lbSyCgxDCxmP0hkPWW/U5nSJHpVKs3KLeE5/YWGo3ibWn16WxoSMUJYJH2ifhEgA6W4pZ7x+9vHmMT2pyfpTKK45NE3P6GHKWv3w0Lt4leXDJyEFbSurbMiDCKfl5r7m8zp3X2tiSkXi9iLr6fVzjzt48FFLDEJkSZXknJjVRAD9eE8+6ZDRxst6T/mlMrJdrQT33wtY0DnVinR2UwLiVfN404ZIh0AOe1/GrccgB5ndK1WGak0QGI46P0BTvBen6,iv:EcDxCtA1KkBTpeiLFCrieShD+CRjrWN/hmOfrENW7ws=,tag:eISTc2Ts/8rrQdcV/lR9oA==,type:str]
    OP_ITEM_NAME: ENC[AES256_GCM,data:i6FlGwhGj3Tg,iv:FDb+fAeNPKL4RPO7nZuUJod+KQMHdf1IM+Fb8qIFnI4=,tag:ONjox/0DveCDP/KsmbFyvw==,type:str]
    OP_VAULT: ENC[AES256_GCM,data:FvePY91yzjnIYUxr,iv:pjZtQ5k7kc8973b74nxULWfJ3JwSJtaI2pFWFaXp5wQ=,tag:6jCt2taRBdw05j039kxBeA==,type:str]
    OFFICE_ID: ENC[AES256_GCM,data:Kr6ocbA=,iv:IMQEylgOA0/l4JD7hrbCKviC8ywxYyAlGlDRdVHVYV4=,tag:uSGJNlagYVXWIkcqde7NqQ==,type:str]
    FLOOR_ID: ENC[AES256_GCM,data:KingZ0Y=,iv:b6Ga8Pq1zZAtcNEOkAO3IJYhQO+tfhbMbpnQxcD1sgo=,tag:cQFiszUW8ABzb16gNNj1Tg==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRDRSOFdOT1lDNmk2VHBR
            ZWlmYmM2d2JaOUV6TXBVMkd1cERHZHZnMjFVCkRiU201c0xnWG1rZEdsSmhyd0Zh
            VmJWVkw2Z2pMT0Q5OXY4ZGxVUFV4VmsKLS0tIEMyTlh2bzlmSnpjcHd3RjNNbDU3
            TE5hNHIvS0dGa21CWjBWVC8vK095S0EK2gmrHcQk8T2GlEE0chv2Mie4L3VCHRAm
            Z4U9MFZsu4uX5pnhRxZ4CGsLPzm6/xNC4j45NyYCqzir5LmtnRQe8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:39:22Z"
    mac: ENC[AES256_GCM,data:a+Ir4JtgraN4Or1Gp9EvQIP6N4CM6CdAbv/4mbkC9ZUV64GScLdz5Q5ity2KfpKHay14N4UkLBkkMfUfnnZdYLUq7+OF8h0IGD1e6S29/1fw+Hnf4DoGD39Vbs/kJWPnGmdvmMq+1dsbCk+bnFEtNYpRMNkotknq2wTVS77fBTY=,iv:ATwd2BhyE4AEjTGGRwoUrQqzXqZBZA0j+OJhxFpa4IQ=,tag:QrR7aF47oW5UdnBN+uZ/iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
